[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
  'pip',
  'beancount',
  'fava',
  'smart_importer',
  'beancount_categorizer',
  'git+https://github.com/bratekarate/beancount-categorizer.git'
]